-- MySQL Script generated by MySQL Workbench
-- Sun 18 Sep 2016 10:17:02 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OurShoppingListDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OurShoppingListDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OurShoppingListDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `OurShoppingListDB` ;

-- -----------------------------------------------------
-- Table `OurShoppingListDB`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurShoppingListDB`.`Categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurShoppingListDB`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurShoppingListDB`.`Items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `buy` TINYINT(1) NOT NULL,
  `category` INT NOT NULL,
  `howmany` INT UNSIGNED NULL,
  PRIMARY KEY (`id`, `category`),
  INDEX `fk_Items_Categories_idx` (`category` ASC),
  CONSTRAINT `fk_Items_Categories`
    FOREIGN KEY (`category`)
    REFERENCES `OurShoppingListDB`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurShoppingListDB`.`Shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurShoppingListDB`.`Shops` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OurShoppingListDB`.`Items_has_Shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OurShoppingListDB`.`Items_has_Shops` (
  `Item` INT UNSIGNED NOT NULL,
  `Shop` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Item`, `Shop`),
  INDEX `fk_Items_has_Shops_Shops1_idx` (`Shop` ASC),
  INDEX `fk_Items_has_Shops_Items1_idx` (`Item` ASC),
  CONSTRAINT `fk_Items_has_Shops_Items1`
    FOREIGN KEY (`Item`)
    REFERENCES `OurShoppingListDB`.`Items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Items_has_Shops_Shops1`
    FOREIGN KEY (`Shop`)
    REFERENCES `OurShoppingListDB`.`Shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
